import type { RawMessage, RawWorkItem } from "./raw";

/**
 * A file on the message, referenced not linked: source download URLs are signed
 * and short-lived (Freshdesk's expire in minutes), and the file is already on
 * the same ticket a transcript is posted to.
 */
export interface CompactAttachment {
  name: string;
  size?: number;
  type?: string;
}

export interface CompactTurn {
  n: number;
  speaker: string;
  at: string;
  kind: "reply" | "internal_note" | "quoted";
  source_message?: string;
  text: string;
  attachments?: CompactAttachment[];
}

export interface CompactStats {
  source_messages: number;
  turns: number;
  raw_chars: number;
  compact_chars: number;
  dropped: {
    automated: number;
    auto_reply: number;
    exact_duplicate_blocks: number;
    near_duplicate_blocks: number;
    boilerplate_lines: number;
    prior_transcript: number;
  };
  /** Quoted messages older than the ticket - history that exists nowhere else. */
  recovered_earlier: number;
  /** Files referenced by name; never re-uploaded, never linked (URLs expire). */
  attachments: number;
}

export interface CompactedWorkItem {
  ticket: {
    external_id: string;
    title?: string;
    url?: string;
    opened?: string;
    updated?: string;
  };
  compaction: CompactStats;
  speakers: string[];
  turns: CompactTurn[];
  /** Source ids of transcripts a previous run posted, so they can be replaced. */
  prior_transcript_ids: string[];
}

export interface CompactOptions {
  /** A line repeated in at least this many blocks is treated as boilerplate. */
  boilerplateThreshold?: number;
  /** An angle-bracket URL repeated at least this often is a tracking link. */
  trackerThreshold?: number;
  /** 5-gram containment above which a block counts as a near-duplicate. */
  nearDuplicateRatio?: number;
  /** Keep automated reminders and out-of-office replies as turns. */
  keepAutomated?: boolean;
}

const MAIL_HEADER_LINE =
  /^\s*(De|From|Von|Da|Van|Enviado(\s+el)?|Sent|Gesendet(\s+am)?|Verzonden|Para|To|An|Aan|Cc|CC|CCO|Bcc|Asunto|Subject|Betreff|Onderwerp|Fecha|Date|Datum|Responder a|Reply-To|Importancia|Priority)\s*:/i;
const WROTE_VERBS =
  "escribió|escreveu|wrote|schrieb|schreef|a écrit|ha scritto|napisał\\(a\\)|napisał|написал\\(а\\)|написал|skrev";
/**
 * The "On 3 May 2024, Ana wrote:" line above a quoted message. `\b` is
 * ASCII-only, so the character before a Cyrillic verb is matched as "not a
 * letter" instead.
 */
const WROTE = new RegExp(
  `^\\s*(?:El|On|Am|Op|Le|Il|Em|W dniu|\\d)[^\\n]{0,200}?[^\\p{L}](?:${WROTE_VERBS})\\s*:?\\s*$`,
  "iu",
);
const WROTE_TAIL = new RegExp(`\\s*(?:${WROTE_VERBS})\\s*:?\\s*$`, "iu");
/** Quoting nested deeper than this is left as text. */
const MAX_QUOTE_DEPTH = 8;
/** Two header lines within this many lines start a quoted message. */
const HEADER_RUN_WINDOW = 6;
const HEADER_RUN_MIN = 2;
/** One level of plain-text quoting; the block below it is history, not new text. */
const QUOTED_LINE = /^\s*>/;
const FROM_LINE = /^\s*(De|From|Von|Da|Van)\s*:\s*(.+)$/i;
const WHEN_LINE =
  /^\s*(Enviado(\s+el)?|Sent|Gesendet(\s+am)?|Fecha|Date|Datum|Verzonden)\s*:\s*(.+)$/i;
const HORIZONTAL_RULE = /^[_\-\u2014=*·]{4,}$/;
/** Placeholder left where an image was, so a reader knows one existed. */
export const IMAGE_MARK = "[image]";

/** Security banners and legal footers that mail gateways and signatures add. */
const BANNERS = [
  /remitente externo/i,
  /EXTERNAL EMAIL/i,
  /correo electrónico externo/i,
  /Tenga cuidado con los enlaces/i,
  /Informar phishing/i,
  /^CONFIDENTIALITY\b/i,
  /Registered Office:/i,
  /Commercial Register/i,
  /VAT identification/i,
  /privacy policy/i,
  /confidential and may also be privileged/i,
  /Connect with us on social/i,
  /^Follow us on/i,
  /Diese E-Mail enthält vertrauliche/i,
];

/**
 * Stamped into every posted transcript. A compacted note becomes a message on
 * the ticket, so without this a second run would compact its own output.
 */
export const TRANSCRIPT_MARKER = "[tachy:compacted-transcript]";

/** A note that carries no marker is recognised by its header. */
const PRIOR_TRANSCRIPT =
  /\[tachy:compacted-transcript\]|^\s*Compacted transcript [\u2014-].{0,200}\bGenerated by tachy\b/s;

/** A longer message that mentions being out of office is a real reply. */
const AUTO_REPLY_MAX_CHARS = 1200;
/** Shorter lines repeat by chance and are never counted as boilerplate. */
const BOILERPLATE_MIN_CHARS = 10;

const AUTO_REPLY =
  /\b(out of office|fuera de la oficina|automatic reply|respuesta automática|abwesenheitsnotiz|nicht im büro|auto[- ]?reply)\b/i;

/** "Name | Role | Company": a signature line when it also holds a phone number. */
const SIGNATURE_LINE = /^[^|\n]{2,60}(\s*\|\s*[^|\n]{0,60}){1,4}\s*:?\s*$/;
const PHONE = /(\+\d{1,3}[\s.-]?)?(\(?\d{2,4}\)?[\s.-]?){2,4}\d{2,4}/;
/** "Calle Mayor 1, 28001, Madrid". */
const POSTAL = /^[^,\n]{3,60},\s*\d{4,6},?\s*[A-Za-zÁÉÍÓÚÑáéíóúñ .'-]{2,40}$/;

const MONTHS: Record<string, number> = {
  enero: 0,
  febrero: 1,
  marzo: 2,
  abril: 3,
  mayo: 4,
  junio: 5,
  julio: 6,
  agosto: 7,
  septiembre: 8,
  setiembre: 8,
  octubre: 9,
  noviembre: 10,
  diciembre: 11,
  january: 0,
  february: 1,
  march: 2,
  april: 3,
  may: 4,
  june: 5,
  july: 6,
  august: 7,
  september: 8,
  october: 9,
  november: 10,
  december: 11,
  januar: 0,
  februar: 1,
  märz: 2,
  mai: 4,
  juni: 5,
  juli: 6,
  oktober: 9,
  dezember: 11,
};

const nonEmpty = (v: unknown): string | undefined =>
  typeof v === "string" && v.trim() ? v.trim() : undefined;

/**
 * Attachment payloads differ per source (Freshdesk `name`/`content_type`/`size`,
 * Jira `filename`/`mimeType`/`size`), so the shape is duck-typed rather than
 * imported - a new adapter needs no change here.
 */
export function normalizeAttachments(input: unknown): CompactAttachment[] {
  if (!Array.isArray(input)) return [];
  const attachments: CompactAttachment[] = [];
  for (const entry of input) {
    if (!entry || typeof entry !== "object") continue;
    const fields = entry as Record<string, unknown>;
    const name =
      nonEmpty(fields.name) ??
      nonEmpty(fields.filename) ??
      nonEmpty(fields.file_name);
    if (!name) continue;
    const size =
      typeof fields.size === "number" && fields.size >= 0
        ? fields.size
        : undefined;
    const type =
      nonEmpty(fields.content_type) ??
      nonEmpty(fields.contentType) ??
      nonEmpty(fields.mimeType) ??
      nonEmpty(fields.mime_type);
    attachments.push({
      name,
      ...(size != null ? { size } : {}),
      ...(type ? { type } : {}),
    });
  }
  return attachments;
}

export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export const describeAttachment = (attachment: CompactAttachment): string => {
  const meta = [
    attachment.size != null ? formatBytes(attachment.size) : null,
    attachment.type,
  ]
    .filter(Boolean)
    .join(", ");
  return meta ? `${attachment.name} (${meta})` : attachment.name;
};

const decode = (u: string) => {
  try {
    return decodeURIComponent(u);
  } catch {
    return u;
  }
};

/** Recover the real target from corporate link-rewriting wrappers. */
function unwrapLinks(text: string): string {
  return text
    .replace(
      /https?:\/\/[\w.-]*safelinks\.protection\.outlook\.com\/[^\s<>"]*[?&]url=([^&\s<>"]+)[^\s<>"]*/gi,
      (_m, u) => decode(u),
    )
    .replace(
      /https?:\/\/secure-web\.cisco\.com\/[^\s<>"]*?\/(https?(?:%3A|:)[^\s<>"]+)/gi,
      (_m, u) => decode(u),
    )
    .replace(
      /https?:\/\/urldefense\.[\w.]+\/v\d\/__([^_\s<>"]+)__[^\s<>"]*/gi,
      (_m, u) => decode(u),
    );
}

/**
 * Freshdesk's `*_text` fields collapse hard newlines into runs of spaces, so
 * long runs are restored as paragraph breaks before anything else looks at
 * line structure. Only runs *between* text count - a run at the start of a
 * line is indentation, and shredding that would destroy pasted JSON and code.
 */
export function normalizeBody(input: string | undefined): string {
  return (
    unwrapLinks(input ?? "")
      .replace(/\r\n/g, "\n")
      .replace(/[\u00a0\u200b]/g, " ")
      .replace(/<mailto:[^>]*>/gi, "")
      // The reference is unusable outside the mail; the marker records the image.
      .replace(/\[cid:[^\]]+\]/gi, IMAGE_MARK)
      .replace(
        /\[(Imagen quitada por el remitente\.?|Image|Imagen|Bild entfernt)[^\]]*\]/gi,
        IMAGE_MARK,
      )
      .replace(/https?:\/\/attachment\.[\w.-]+\/inline\/\S+/gi, IMAGE_MARK)
      .replace(/\[[A-Za-z]:\\[^\]]*\]/g, "")
      .replace(/\[[/~][^\]]{3,}\]/g, "")
      .replace(/\uFFFC/g, "")
      .replace(/(?<=\S)[ \t]{4,}(?=\S)/g, "\n\n")
      .replace(/[ \t]+$/gm, "")
      // A run of images, as in a signature of logos, becomes one marker.
      .replace(/(?:\[image\][ \t]*){2,}/g, IMAGE_MARK)
      .replace(/\n{3,}/g, "\n\n")
      .trim()
  );
}

export function parseMailDate(input: string | undefined): Date | null {
  if (!input) return null;
  const text = input.trim();
  const spanish =
    /(\d{1,2})\s+de\s+([a-záéíóúü]+)\s+de\s+(\d{4})(?:[,\s]+(\d{1,2})[:.](\d{2}))?/i.exec(
      text,
    );
  if (spanish && MONTHS[spanish[2].toLowerCase()] != null)
    return new Date(
      Date.UTC(
        +spanish[3],
        MONTHS[spanish[2].toLowerCase()],
        +spanish[1],
        +(spanish[4] ?? 0),
        +(spanish[5] ?? 0),
      ),
    );
  const german =
    /(\d{1,2})\.\s*([A-Za-zäöü]+)\s+(\d{4})(?:\s+(\d{1,2}):(\d{2}))?/.exec(
      text,
    );
  if (german && MONTHS[german[2].toLowerCase()] != null)
    return new Date(
      Date.UTC(
        +german[3],
        MONTHS[german[2].toLowerCase()],
        +german[1],
        +(german[4] ?? 0),
        +(german[5] ?? 0),
      ),
    );
  const numeric = /(\d{1,2})\/(\d{1,2})\/(\d{4})(?:\s+(\d{1,2}):(\d{2}))?/.exec(
    text,
  );
  if (numeric)
    return new Date(
      Date.UTC(
        +numeric[3],
        +numeric[2] - 1,
        +numeric[1],
        +(numeric[4] ?? 0),
        +(numeric[5] ?? 0),
      ),
    );
  const parsed = new Date(text);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
}

interface Block {
  quoted: boolean;
  from: string | null;
  when: Date | null;
  text: string;
}

/**
 * Split one message into its own text plus every quoted hop below it. Each hop
 * keeps the sender and date off its header, so content that only ever survived
 * inside a quote can still be attributed and placed in time.
 */
export function splitQuotedBlocks(text: string, depth = 0): Block[] {
  const lines = text.split("\n");
  const blocks: Block[] = [];
  let pending: string[] = [];
  let from: string | null = null;
  let when: Date | null = null;
  let quoted = false;

  const flush = () => {
    const joined = pending.join("\n").trim();
    if (joined) blocks.push({ quoted, from, when, text: joined });
    pending = [];
  };

  const isHeaderRun = (i: number) => {
    if (!MAIL_HEADER_LINE.test(lines[i])) return false;
    let headerLines = 0;
    const end = Math.min(lines.length, i + HEADER_RUN_WINDOW);
    for (let j = i; j < end; j++)
      if (MAIL_HEADER_LINE.test(lines[j])) headerLines++;
    return headerLines >= HEADER_RUN_MIN;
  };

  for (let i = 0; i < lines.length; i++) {
    // A run of ">" lines is one quoting level: strip it and re-split what is
    // inside, so a chain nested three deep still yields one turn per hop.
    if (QUOTED_LINE.test(lines[i]) && depth < MAX_QUOTE_DEPTH) {
      flush();
      let j = i;
      while (
        j < lines.length &&
        (QUOTED_LINE.test(lines[j]) || !lines[j].trim())
      )
        j++;
      const inner = lines
        .slice(i, j)
        .map((l) => l.replace(/^\s*>\s?/, ""))
        .join("\n");
      for (const nested of splitQuotedBlocks(inner, depth + 1))
        blocks.push({
          ...nested,
          quoted: true,
          from: nested.from ?? from,
          when: nested.when ?? when,
        });
      i = j - 1;
      quoted = true;
      continue;
    }
    if (isHeaderRun(i) || WROTE.test(lines[i])) {
      flush();
      quoted = true;
      let j = i;
      let sender: string | null = null;
      let dateText: string | null = null;
      if (WROTE.test(lines[i])) {
        sender = lines[i]
          .replace(/^\s*(El|On|Am|Op|Le|Il|Em|W dniu)\s+/i, "")
          .replace(WROTE_TAIL, "");
        dateText = sender;
        j = i + 1;
      } else {
        while (
          j < lines.length &&
          (MAIL_HEADER_LINE.test(lines[j]) || !lines[j].trim())
        ) {
          const fromMatch = FROM_LINE.exec(lines[j]);
          if (fromMatch && !sender) sender = fromMatch[2].trim();
          const whenMatch = WHEN_LINE.exec(lines[j]);
          if (whenMatch && !dateText) dateText = whenMatch[4].trim();
          j++;
        }
      }
      from = sender;
      when = parseMailDate(dateText ?? undefined);
      i = j - 1;
      continue;
    }
    pending.push(lines[i]);
  }
  flush();
  return blocks;
}

const CODE_LIKE_LINE =
  /^\s*[{}[\]]|^\s*"[^"]*"\s*:|^\s*<\/?\w|^\s*(?:function|const|let|var|import|def|class|SELECT|INSERT|UPDATE|<\?xml)\b|^\s{2,}\S|[;,{}]\s*$/;

const STRUCTURED_MIN_LINES = 3;
/** The share of code-like lines that makes a paragraph structured. */
const STRUCTURED_RATIO = 0.6;

/**
 * Pasted JSON, XML, logs and stack traces are evidence: their repeated lines
 * are structure, not boilerplate, and two payloads differing in one field are
 * not near-duplicates. Such blocks are kept verbatim and compared whole.
 */
export function looksStructured(paragraph: string): boolean {
  const lines = paragraph.split("\n").filter((l) => l.trim());
  if (lines.length < STRUCTURED_MIN_LINES) return false;
  const hits = lines.filter((l) => CODE_LIKE_LINE.test(l)).length;
  return hits / lines.length >= STRUCTURED_RATIO;
}

const lineKey = (s: string) => s.toLowerCase().replace(/\s+/g, " ").trim();

const tokens = (s: string) =>
  s
    .toLowerCase()
    .replace(/^\s*>+/gm, "")
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .trim()
    .split(" ")
    .filter(Boolean);

function shingles(s: string, size = 5): Set<string> {
  const words = tokens(s);
  const grams = new Set<string>();
  for (let i = 0; i + size <= words.length; i++)
    grams.add(words.slice(i, i + size).join(" "));
  return grams;
}

const blockKey = (s: string) => tokens(s).join(" ");

function displayName(raw: string): string {
  const quotedName = /^"?([^"<]+?)"?\s*</.exec(raw);
  let name = (quotedName?.[1] ?? raw).replace(/<[^>]*>/g, "").trim();
  if (name.includes("@")) return name.toLowerCase();
  if (name.includes(","))
    name = name.split(",").reverse().join(" ").replace(/\s+/g, " ").trim();
  return name || "unknown";
}

export interface CompactMeta {
  externalId: string;
  title?: string;
  url?: string;
  opened?: string;
  updated?: string;
}

/**
 * Reduce a work item's messages to a de-duplicated, attributed turn list.
 * Deterministic - no model calls, same input always yields the same output.
 */
export function compactMessages(
  messages: RawMessage[],
  meta: CompactMeta,
  opts: CompactOptions = {},
): CompactedWorkItem {
  const boilerplateThreshold = opts.boilerplateThreshold ?? 3;
  const trackerThreshold = opts.trackerThreshold ?? 5;
  const nearRatio = opts.nearDuplicateRatio ?? 0.8;

  const bodies = messages.map((m) => normalizeBody(m.bodyText));
  const rawChars = bodies.reduce((a, b) => a + b.length, 0);
  const blocksPerMessage = bodies.map(splitQuotedBlocks);

  const lineFreq = new Map<string, number>();
  const urlFreq = new Map<string, number>();
  for (const blocks of blocksPerMessage)
    for (const block of blocks) {
      const seen = new Set<string>();
      for (const line of block.text.split("\n")) {
        const key = lineKey(line);
        if (key.length < BOILERPLATE_MIN_CHARS || seen.has(key)) continue;
        seen.add(key);
        lineFreq.set(key, (lineFreq.get(key) ?? 0) + 1);
      }
      for (const link of block.text.matchAll(/<(https?:\/\/[^>]+)>/g))
        urlFreq.set(link[1], (urlFreq.get(link[1]) ?? 0) + 1);
    }
  const boilerplate = new Set(
    [...lineFreq].filter(([, n]) => n >= boilerplateThreshold).map(([k]) => k),
  );
  const trackers = new Set(
    [...urlFreq].filter(([, n]) => n >= trackerThreshold).map(([u]) => u),
  );

  const detrack = (s: string) =>
    s
      .replace(/<(https?:\/\/[^>]+)>/g, (m, u) => (trackers.has(u) ? "" : m))

      .replace(/[ \t]{2,}/g, " ")
      .trim();

  const dropped = {
    automated: 0,
    auto_reply: 0,
    prior_transcript: 0,
    exact_duplicate_blocks: 0,
    near_duplicate_blocks: 0,
    boilerplate_lines: 0,
  };

  const emitted = new Set<string>();
  /**
   * Banners, rules and signatures are noise wherever they appear. A repeated
   * line is noise only on re-appearance: a ticket's own description recurs once
   * every later mail quotes it, and the original must survive.
   */
  const isNoise = (line: string) => {
    const text = line.trim();
    if (!text) return false;
    if (BANNERS.some((r) => r.test(text))) return true;
    if (HORIZONTAL_RULE.test(text)) return true;
    if (POSTAL.test(text)) return true;
    if (SIGNATURE_LINE.test(text) && PHONE.test(text)) return true;
    const key = lineKey(text);
    if (boilerplate.has(key)) {
      if (emitted.has(key)) return true;
      emitted.add(key);
    }
    return false;
  };

  const seenBlocks = new Set<string>();
  const seenShingles = new Set<string>();
  const keepBlock = (text: string, structured = false) => {
    const key = blockKey(text);
    if (!key) return false;
    if (seenBlocks.has(key)) {
      dropped.exact_duplicate_blocks++;
      return false;
    }
    seenBlocks.add(key);
    if (structured) return true;
    const grams = shingles(text);
    if (grams.size >= 3) {
      let repeated = 0;
      for (const g of grams) if (seenShingles.has(g)) repeated++;
      if (repeated / grams.size >= nearRatio) {
        dropped.near_duplicate_blocks++;
        return false;
      }
    }
    for (const g of grams) seenShingles.add(g);
    return true;
  };

  const skipped = messages.map((msg, idx) => {
    const body = bodies[idx];
    if (!body) return null;
    if (PRIOR_TRANSCRIPT.test(body)) return "prior_transcript" as const;
    if (opts.keepAutomated) return null;
    if (msg.automated) return "automated" as const;
    if (AUTO_REPLY.test(body) && body.length < AUTO_REPLY_MAX_CHARS)
      return "auto_reply" as const;
    return null;
  });
  skipped.forEach((why, idx) => {
    if (!why) return;
    dropped[why]++;
    for (const line of bodies[idx].split("\n")) emitted.add(lineKey(line));
  });

  const turns: CompactTurn[] = [];
  const messageFilesPlaced = new Set<number>();
  let attachmentCount = 0;
  messages.forEach((msg, idx) => {
    const body = bodies[idx];
    if (!body || skipped[idx]) return;
    const internal = msg.visibility !== "public";
    const ownKind = internal ? "internal_note" : "reply";
    // `authorLabel` is the adapter's display name; `author` (a login or id) is
    // the fallback, so a source that sets only that names people.
    const author =
      msg.authorLabel ??
      msg.author ??
      (internal ? "agent (internal)" : "support");
    const turnsBefore = turns.length;
    for (const block of blocksPerMessage[idx]) {
      const paragraphs = block.text
        .split(/\n\s*\n/)
        .map((paragraph) => {
          if (looksStructured(paragraph)) return paragraph.replace(/\s+$/, "");
          return detrack(paragraph)
            .split("\n")
            .map(detrack)
            .filter((line) => {
              if (!isNoise(line)) return true;
              dropped.boilerplate_lines++;
              return false;
            })
            .join("\n")
            .trim();
        })
        .filter(
          (p) => p.trim().length >= 3 && keepBlock(p, looksStructured(p)),
        );
      if (!paragraphs.length) continue;
      turns.push({
        n: turns.length + 1,
        speaker: block.quoted ? displayName(block.from ?? "unknown") : author,
        at:
          block.quoted && block.when
            ? block.when.toISOString()
            : (msg.createdAt ?? meta.opened ?? ""),
        kind: block.quoted ? "quoted" : ownKind,
        source_message: msg.externalId,
        text: paragraphs.join("\n\n"),
      });
      // Files belong to the message: they go on its first surviving turn, not
      // under every quoted hop.
      if (!block.quoted && !messageFilesPlaced.has(idx)) {
        const files = normalizeAttachments(msg.attachments);
        if (files.length) {
          turns[turns.length - 1].attachments = files;
          attachmentCount += files.length;
        }
        messageFilesPlaced.add(idx);
      }
    }
    if (messageFilesPlaced.has(idx)) return;
    const files = normalizeAttachments(msg.attachments);
    if (!files.length) return;
    messageFilesPlaced.add(idx);
    attachmentCount += files.length;
    const own = turns.slice(turnsBefore).find((t) => t.kind !== "quoted");
    if (own) {
      own.attachments = files;
      return;
    }
    // Every paragraph was a duplicate: the files get a turn of their own, so
    // the reference survives.
    turns.push({
      n: turns.length + 1,
      speaker: author,
      at: msg.createdAt ?? meta.opened ?? "",
      kind: ownKind,
      source_message: msg.externalId,
      text: "",
      attachments: files,
    });
  });

  const opened = meta.opened ? Date.parse(meta.opened) : NaN;
  const recovered = Number.isNaN(opened)
    ? 0
    : turns.filter((t) => t.kind === "quoted" && Date.parse(t.at) < opened)
        .length;

  return {
    ticket: {
      external_id: meta.externalId,
      title: meta.title,
      url: meta.url,
      opened: meta.opened,
      updated: meta.updated,
    },
    compaction: {
      source_messages: messages.length,
      turns: turns.length,
      raw_chars: rawChars,
      compact_chars: turns.reduce((a, t) => a + t.text.length, 0),
      dropped,
      recovered_earlier: recovered,
      attachments: attachmentCount,
    },
    speakers: [...new Set(turns.map((t) => t.speaker))],
    turns,
    prior_transcript_ids: messages
      .filter((m, i) => skipped[i] === "prior_transcript" && m.externalId)
      .map((m) => m.externalId as string),
  };
}

export function compactWorkItem(
  item: RawWorkItem,
  opts: CompactOptions = {},
): CompactedWorkItem {
  return compactMessages(
    item.messages,
    {
      externalId: item.externalId,
      title: item.title,
      url: item.externalUrl,
      opened: item.sourceCreatedAt,
      updated: item.sourceUpdatedAt,
    },
    opts,
  );
}

/** Below this much message text, reshaping a ticket buys nothing. */
export const COMPACT_MIN_CHARS = 8 * 1024;
/** The share of the text compaction must remove to be used. */
export const COMPACT_MIN_SAVING = 0.2;

/**
 * Whether the model reads the compacted form instead of the raw messages.
 * Compaction is pure CPU, so it is always computed and kept only past both
 * thresholds: a short ticket, or a long one with no repetition, comes back
 * unchanged.
 */
export function compactForLlm(
  item: RawWorkItem,
  opts: CompactOptions = {},
): { item: RawWorkItem; compacted?: CompactedWorkItem } {
  const compacted = compactWorkItem(item, opts);
  const { raw_chars, compact_chars } = compacted.compaction;
  if (raw_chars < COMPACT_MIN_CHARS) return { item };
  const saving = raw_chars ? (raw_chars - compact_chars) / raw_chars : 0;
  if (saving < COMPACT_MIN_SAVING) return { item };
  return { item: { ...item, messages: [] }, compacted };
}

/**
 * Quoted turns older than the work item itself came from mail that predates the
 * ticket and exists nowhere else, so they read as their own timeline.
 */
export function splitPrologue(compacted: CompactedWorkItem): {
  prologue: CompactTurn[];
  thread: CompactTurn[];
} {
  const opened = compacted.ticket.opened
    ? Date.parse(compacted.ticket.opened)
    : NaN;
  if (Number.isNaN(opened)) return { prologue: [], thread: compacted.turns };
  const prologue: CompactTurn[] = [];
  const thread: CompactTurn[] = [];
  for (const turn of compacted.turns) {
    const at = Date.parse(turn.at);
    if (turn.kind === "quoted" && !Number.isNaN(at) && at < opened)
      prologue.push(turn);
    else thread.push(turn);
  }
  prologue.sort((a, b) => a.at.localeCompare(b.at));
  return { prologue, thread };
}

const day = (s: string) => (s || "").slice(0, 10);

const KIND_TAG: Record<CompactTurn["kind"], string> = {
  quoted: " ↩quoted",
  internal_note: " ·internal",
  reply: "",
};
const tag = (t: CompactTurn) => KIND_TAG[t.kind];

export function renderCompactScript(compacted: CompactedWorkItem): string {
  const { prologue, thread } = splitPrologue(compacted);
  const summary = summarizeCompaction(compacted);
  const lines: string[] = [
    `# ${compacted.ticket.title ?? "Work item"}   [#${compacted.ticket.external_id}]`,
    "",
    `${summary.headline} · ${day(compacted.ticket.opened ?? "")} → ${day(compacted.ticket.updated ?? "")}`,
    [summary.removed, summary.recovered, summary.files]
      .filter(Boolean)
      .join(" "),
    "",
  ];
  const renderTurn = (turn: CompactTurn, withTag: boolean) =>
    `${turn.speaker} (${day(turn.at)})${withTag ? tag(turn) : ""}:${
      turn.text ? ` ${turn.text.replace(/\n/g, "\n    ")}` : ""
    }\n` +
    (turn.attachments?.length
      ? `    ↳ files: ${turn.attachments.map(describeAttachment).join("; ")}\n`
      : "");
  if (prologue.length) {
    lines.push(
      `## Earlier mail, recovered from quoted replies - ${prologue.length} message${prologue.length === 1 ? "" : "s"} that appear nowhere else on this ticket`,
      "",
    );
    for (const t of prologue) lines.push(renderTurn(t, false));
    lines.push(`## The ticket thread`, "");
  }
  for (const t of thread) lines.push(renderTurn(t, true));
  return lines.join("\n");
}

const escapeHtml = (s: string) =>
  s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const SPEAKER_COLOR: Record<CompactTurn["kind"], string> = {
  reply: "#1a1a1a",
  internal_note: "#8a5a00",
  quoted: "#5a5a7a",
};

const roundedKb = (n: number) => `${Math.max(1, Math.round(n / 1024))} KB`;

/**
 * Plain-language accounting of what changed. "Turns" and "blocks" are internal
 * vocabulary - a reader wants to know how much less there is to read, what was
 * taken away, and what was found.
 */
export function summarizeCompaction(compacted: CompactedWorkItem): {
  headline: string;
  removed: string;
  recovered: string;
  files: string;
} {
  const { raw_chars, compact_chars, source_messages, dropped } =
    compacted.compaction;
  const saved = raw_chars
    ? Math.max(0, Math.round((100 * (raw_chars - compact_chars)) / raw_chars))
    : 0;
  const removals: string[] = [];
  const repeats =
    dropped.exact_duplicate_blocks + dropped.near_duplicate_blocks;
  if (repeats)
    removals.push(`${repeats} repeated quote${repeats === 1 ? "" : "s"}`);
  if (dropped.boilerplate_lines)
    removals.push(`${dropped.boilerplate_lines} signature/footer lines`);
  const automated = dropped.automated + dropped.auto_reply;
  if (automated)
    removals.push(`${automated} automated mail${automated === 1 ? "" : "s"}`);
  if (dropped.prior_transcript) removals.push("an earlier transcript");
  const files = compacted.compaction.attachments;
  return {
    headline: `${source_messages} messages · ${roundedKb(compact_chars)} to read instead of ${roundedKb(raw_chars)} (${saved}% less)`,
    files: files
      ? `${files} file${files === 1 ? "" : "s"} referenced by name - open them on the ticket.`
      : "",
    removed: removals.length ? `Removed ${removals.join(", ")}.` : "",
    recovered: compacted.compaction.recovered_earlier
      ? `Recovered ${compacted.compaction.recovered_earlier} older message${compacted.compaction.recovered_earlier === 1 ? "" : "s"} that survive only inside quoted replies.`
      : "",
  };
}

/** Freshdesk note bodies render HTML, so the script ships as markup, not markdown. */
export function renderCompactHtml(compacted: CompactedWorkItem): string {
  const { prologue, thread } = splitPrologue(compacted);
  const summary = summarizeCompaction(compacted);
  const renderTurn = (turn: CompactTurn, withTag: boolean) =>
    `<p style="margin:0 0 10px 0"><strong style="color:${SPEAKER_COLOR[turn.kind]}">${escapeHtml(turn.speaker)}</strong> ` +
    `<span style="color:#888">(${day(turn.at)})${withTag ? escapeHtml(tag(turn)) : ""}</span>:${turn.text ? " " : ""}` +
    `${escapeHtml(turn.text)
      .replace(/\n\s*\n/g, "<br><br>")
      .replace(/\n/g, "<br>")}` +
    (turn.attachments?.length
      ? `<br><span style="color:#777">↳ files: ${escapeHtml(turn.attachments.map(describeAttachment).join("; "))}</span>`
      : "") +
    `</p>`;
  const parts: string[] = [
    `<div><p><strong>Compacted transcript - ${escapeHtml(compacted.ticket.title ?? "")} [#${escapeHtml(compacted.ticket.external_id)}]</strong></p>`,
    `<p style="color:#666">${escapeHtml(summary.headline)}<br>${escapeHtml([summary.removed, summary.recovered, summary.files].filter(Boolean).join(" "))}<br>` +
      `Every word below is quoted verbatim - nothing was summarised or reworded. ` +
      `Generated by tachy ${TRANSCRIPT_MARKER}</p><hr>`,
  ];
  if (prologue.length) {
    parts.push(
      `<p><strong>Earlier mail, recovered from quoted replies</strong> - ${prologue.length} message${prologue.length === 1 ? "" : "s"} that appear nowhere else on this ticket</p>`,
    );
    for (const t of prologue) parts.push(renderTurn(t, false));
    parts.push(`<hr><p><strong>The ticket thread</strong></p>`);
  }
  for (const t of thread) parts.push(renderTurn(t, true));
  parts.push("</div>");
  return parts.join("\n");
}

/**
 * Split a rendered note at turn boundaries. Freshdesk documents no body limit,
 * so a long transcript is posted as a numbered series, not as one oversized
 * request.
 */
export function splitNoteBody(html: string, maxChars = 60000): string[] {
  if (html.length <= maxChars) return [html];
  const paragraphs = html.split("\n");
  const parts: string[] = [];
  let pending: string[] = [];
  let size = 0;
  for (const paragraph of paragraphs) {
    if (size + paragraph.length > maxChars && pending.length) {
      parts.push(pending.join("\n"));
      pending = [];
      size = 0;
    }
    pending.push(paragraph);
    size += paragraph.length + 1;
  }
  if (pending.length) parts.push(pending.join("\n"));
  // Every part carries the marker. Without it parts 2..n come back as
  // ordinary messages, are missed by `prior_transcript_ids`, and
  // `replace_previous` deletes part 1 only.
  return parts.map(
    (part, i) =>
      `<p style="color:#888">[compacted transcript ${i + 1}/${parts.length}] ${TRANSCRIPT_MARKER}</p>\n${part}`,
  );
}
