import type { RawMessage, RawWorkItem } from "../types";

/**
 * A file on the message, referenced not linked: source download URLs are signed
 * and short-lived (Freshdesk's expire in minutes), and the file is already on
 * the same ticket a transcript is posted to.
 */
export interface CompactAttachment {
  name: string;
  size?: number;
  type?: string;
}

export interface CompactTurn {
  n: number;
  speaker: string;
  at: string;
  kind: "reply" | "internal_note" | "quoted";
  source_message?: string;
  text: string;
  attachments?: CompactAttachment[];
}

export interface CompactStats {
  source_messages: number;
  turns: number;
  raw_chars: number;
  compact_chars: number;
  dropped: {
    automated: number;
    auto_reply: number;
    exact_duplicate_blocks: number;
    near_duplicate_blocks: number;
    boilerplate_lines: number;
    prior_transcript: number;
  };
  /** Quoted messages older than the ticket — history that exists nowhere else. */
  recovered_earlier: number;
  /** Files referenced by name; never re-uploaded, never linked (URLs expire). */
  attachments: number;
}

export interface CompactedWorkItem {
  ticket: {
    external_id: string;
    title?: string;
    url?: string;
    opened?: string;
    updated?: string;
  };
  compaction: CompactStats;
  speakers: string[];
  turns: CompactTurn[];
  /** Source ids of transcripts a previous run posted, so they can be replaced. */
  prior_transcript_ids: string[];
}

export interface CompactOptions {
  /** A line repeated in at least this many blocks is treated as boilerplate. */
  boilerplateThreshold?: number;
  /** An angle-bracket URL repeated at least this often is a tracking link. */
  trackerThreshold?: number;
  /** 5-gram containment above which a block counts as a near-duplicate. */
  nearDuplicateRatio?: number;
  /** Keep automated reminders and out-of-office replies as turns. */
  keepAutomated?: boolean;
}

const HEADER =
  /^\s*(De|From|Von|Da|Van|Enviado(\s+el)?|Sent|Gesendet(\s+am)?|Verzonden|Para|To|An|Aan|Cc|CC|CCO|Bcc|Asunto|Subject|Betreff|Onderwerp|Fecha|Date|Datum|Responder a|Reply-To|Importancia|Priority)\s*:/i;
const WROTE_VERBS =
  "escribió|escreveu|wrote|schrieb|schreef|a écrit|ha scritto|napisał\\(a\\)|napisał|написал\\(а\\)|написал|skrev";
// \b is ASCII-only, so a Cyrillic verb never sits on a word boundary: the
// preceding character is matched explicitly as "not a letter" instead.
const WROTE = new RegExp(
  `^\\s*(?:El|On|Am|Op|Le|Il|Em|W dniu|\\d)[^\\n]{0,200}?[^\\p{L}](?:${WROTE_VERBS})\\s*:?\\s*$`,
  "iu",
);
const WROTE_TAIL = new RegExp(`\\s*(?:${WROTE_VERBS})\\s*:?\\s*$`, "iu");
/** One level of plain-text quoting; the block below it is history, not new text. */
const QUOTED_LINE = /^\s*>/;
const FROM_LINE = /^\s*(De|From|Von|Da|Van)\s*:\s*(.+)$/i;
const WHEN_LINE =
  /^\s*(Enviado(\s+el)?|Sent|Gesendet(\s+am)?|Fecha|Date|Datum|Verzonden)\s*:\s*(.+)$/i;
const RULE = /^[_\-—=*·]{4,}$/;
/** Placeholder left where an image was, so a reader knows one existed. */
export const IMAGE_MARK = "[image]";

const BANNERS = [
  /remitente externo/i,
  /EXTERNAL EMAIL/i,
  /correo electrónico externo/i,
  /Tenga cuidado con los enlaces/i,
  /Informar phishing/i,
  /^CONFIDENTIALITY\b/i,
  /Registered Office:/i,
  /Commercial Register/i,
  /VAT identification/i,
  /privacy policy/i,
  /confidential and may also be privileged/i,
  /Connect with us on social/i,
  /^Follow us on/i,
  /Diese E-Mail enthält vertrauliche/i,
];

/**
 * Stamped into every posted transcript. A compacted note becomes a message on
 * the ticket, so without this a second run would compact its own output.
 */
export const TRANSCRIPT_MARKER = "[tachy:compacted-transcript]";

/** The marker is recent; notes posted before it are recognised by their header. */
const PRIOR_TRANSCRIPT =
  /\[tachy:compacted-transcript\]|^\s*Compacted transcript —.{0,200}\bGenerated by tachy\b/s;

const AUTO_REPLY =
  /\b(out of office|fuera de la oficina|automatic reply|respuesta automática|abwesenheitsnotiz|nicht im büro|auto[- ]?reply)\b/i;

const SIGNATURE_LINE = /^[^|\n]{2,60}(\s*\|\s*[^|\n]{0,60}){1,4}\s*:?\s*$/;
const PHONE = /(\+\d{1,3}[\s.-]?)?(\(?\d{2,4}\)?[\s.-]?){2,4}\d{2,4}/;
const POSTAL = /^[^,\n]{3,60},\s*\d{4,6},?\s*[A-Za-zÁÉÍÓÚÑáéíóúñ .'-]{2,40}$/;

const MONTHS: Record<string, number> = {
  enero: 0,
  febrero: 1,
  marzo: 2,
  abril: 3,
  mayo: 4,
  junio: 5,
  julio: 6,
  agosto: 7,
  septiembre: 8,
  setiembre: 8,
  octubre: 9,
  noviembre: 10,
  diciembre: 11,
  january: 0,
  february: 1,
  march: 2,
  april: 3,
  may: 4,
  june: 5,
  july: 6,
  august: 7,
  september: 8,
  october: 9,
  november: 10,
  december: 11,
  januar: 0,
  februar: 1,
  märz: 2,
  mai: 4,
  juni: 5,
  juli: 6,
  oktober: 9,
  dezember: 11,
};

const str = (v: unknown): string | undefined =>
  typeof v === "string" && v.trim() ? v.trim() : undefined;

/**
 * Attachment payloads differ per source (Freshdesk `name`/`content_type`/`size`,
 * Jira `filename`/`mimeType`/`size`), so the shape is duck-typed rather than
 * imported — a new adapter needs no change here.
 */
export function normalizeAttachments(input: unknown): CompactAttachment[] {
  if (!Array.isArray(input)) return [];
  const out: CompactAttachment[] = [];
  for (const a of input) {
    if (!a || typeof a !== "object") continue;
    const r = a as Record<string, unknown>;
    const name = str(r.name) ?? str(r.filename) ?? str(r.file_name);
    if (!name) continue;
    const size = typeof r.size === "number" && r.size >= 0 ? r.size : undefined;
    const type =
      str(r.content_type) ??
      str(r.contentType) ??
      str(r.mimeType) ??
      str(r.mime_type);
    out.push({
      name,
      ...(size != null ? { size } : {}),
      ...(type ? { type } : {}),
    });
  }
  return out;
}

export function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${Math.round(n / 1024)} KB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}

export const describeAttachment = (a: CompactAttachment): string => {
  const meta = [a.size != null ? formatBytes(a.size) : null, a.type]
    .filter(Boolean)
    .join(", ");
  return meta ? `${a.name} (${meta})` : a.name;
};

const decode = (u: string) => {
  try {
    return decodeURIComponent(u);
  } catch {
    return u;
  }
};

/** Recover the real target from corporate link-rewriting wrappers. */
function unwrapLinks(s: string): string {
  return s
    .replace(
      /https?:\/\/[\w.-]*safelinks\.protection\.outlook\.com\/[^\s<>"]*[?&]url=([^&\s<>"]+)[^\s<>"]*/gi,
      (_m, u) => decode(u),
    )
    .replace(
      /https?:\/\/secure-web\.cisco\.com\/[^\s<>"]*?\/(https?(?:%3A|:)[^\s<>"]+)/gi,
      (_m, u) => decode(u),
    )
    .replace(
      /https?:\/\/urldefense\.[\w.]+\/v\d\/__([^_\s<>"]+)__[^\s<>"]*/gi,
      (_m, u) => decode(u),
    );
}

/**
 * Freshdesk's `*_text` fields collapse hard newlines into runs of spaces, so
 * long runs are restored as paragraph breaks before anything else looks at
 * line structure. Only runs *between* text count — a run at the start of a
 * line is indentation, and shredding that would destroy pasted JSON and code.
 */
export function normalizeBody(input: string | undefined): string {
  return (
    unwrapLinks(input ?? "")
      .replace(/\r\n/g, "\n")
      .replace(/[ ​]/g, " ")
      .replace(/<mailto:[^>]*>/gi, "")
      // an image was here: keep the fact, drop the unusable reference
      .replace(/\[cid:[^\]]+\]/gi, IMAGE_MARK)
      .replace(
        /\[(Imagen quitada por el remitente\.?|Image|Imagen|Bild entfernt)[^\]]*\]/gi,
        IMAGE_MARK,
      )
      .replace(/https?:\/\/attachment\.[\w.-]+\/inline\/\S+/gi, IMAGE_MARK)
      .replace(/\[[A-Za-z]:\\[^\]]*\]/g, "")
      .replace(/\[[/~][^\]]{3,}\]/g, "")
      .replace(/\uFFFC/g, "")
      .replace(/(?<=\S)[ \t]{4,}(?=\S)/g, "\n\n")
      .replace(/[ \t]+$/gm, "")
      // a logo-strewn signature yields one marker, not ten
      .replace(/(?:\[image\][ \t]*){2,}/g, IMAGE_MARK)
      .replace(/\n{3,}/g, "\n\n")
      .trim()
  );
}

export function parseMailDate(input: string | undefined): Date | null {
  if (!input) return null;
  const s = input.trim();
  const es =
    /(\d{1,2})\s+de\s+([a-záéíóúü]+)\s+de\s+(\d{4})(?:[,\s]+(\d{1,2})[:.](\d{2}))?/i.exec(
      s,
    );
  if (es && MONTHS[es[2].toLowerCase()] != null)
    return new Date(
      Date.UTC(
        +es[3],
        MONTHS[es[2].toLowerCase()],
        +es[1],
        +(es[4] ?? 0),
        +(es[5] ?? 0),
      ),
    );
  const de =
    /(\d{1,2})\.\s*([A-Za-zäöü]+)\s+(\d{4})(?:\s+(\d{1,2}):(\d{2}))?/.exec(s);
  if (de && MONTHS[de[2].toLowerCase()] != null)
    return new Date(
      Date.UTC(
        +de[3],
        MONTHS[de[2].toLowerCase()],
        +de[1],
        +(de[4] ?? 0),
        +(de[5] ?? 0),
      ),
    );
  const dmy = /(\d{1,2})\/(\d{1,2})\/(\d{4})(?:\s+(\d{1,2}):(\d{2}))?/.exec(s);
  if (dmy)
    return new Date(
      Date.UTC(+dmy[3], +dmy[2] - 1, +dmy[1], +(dmy[4] ?? 0), +(dmy[5] ?? 0)),
    );
  const iso = new Date(s);
  return Number.isNaN(iso.getTime()) ? null : iso;
}

interface Block {
  quoted: boolean;
  from: string | null;
  when: Date | null;
  text: string;
}

/**
 * Split one message into its own text plus every quoted hop below it. Each hop
 * keeps the sender and date off its header, so content that only ever survived
 * inside a quote can still be attributed and placed in time.
 */
export function splitQuotedBlocks(text: string, depth = 0): Block[] {
  const lines = text.split("\n");
  const out: Block[] = [];
  let buf: string[] = [];
  let from: string | null = null;
  let when: Date | null = null;
  let quoted = false;

  const flush = () => {
    const t = buf.join("\n").trim();
    if (t) out.push({ quoted, from, when, text: t });
    buf = [];
  };

  const isHeaderRun = (i: number) => {
    if (!HEADER.test(lines[i])) return false;
    let n = 0;
    for (let j = i; j < Math.min(lines.length, i + 6); j++)
      if (HEADER.test(lines[j])) n++;
    return n >= 2;
  };

  for (let i = 0; i < lines.length; i++) {
    // A run of ">" lines is one quoting level: strip it and re-split what is
    // inside, so a chain nested three deep still yields one turn per hop.
    if (QUOTED_LINE.test(lines[i]) && depth < 8) {
      flush();
      let j = i;
      while (
        j < lines.length &&
        (QUOTED_LINE.test(lines[j]) || !lines[j].trim())
      )
        j++;
      const inner = lines
        .slice(i, j)
        .map((l) => l.replace(/^\s*>\s?/, ""))
        .join("\n");
      for (const b of splitQuotedBlocks(inner, depth + 1))
        out.push({
          ...b,
          quoted: true,
          from: b.from ?? from,
          when: b.when ?? when,
        });
      i = j - 1;
      quoted = true;
      continue;
    }
    if (isHeaderRun(i) || WROTE.test(lines[i])) {
      flush();
      quoted = true;
      let j = i;
      let f: string | null = null;
      let w: string | null = null;
      if (WROTE.test(lines[i])) {
        f = lines[i]
          .replace(/^\s*(El|On|Am|Op|Le|Il|Em|W dniu)\s+/i, "")
          .replace(WROTE_TAIL, "");
        w = f;
        j = i + 1;
      } else {
        while (
          j < lines.length &&
          (HEADER.test(lines[j]) || !lines[j].trim())
        ) {
          const a = FROM_LINE.exec(lines[j]);
          if (a && !f) f = a[2].trim();
          const b = WHEN_LINE.exec(lines[j]);
          if (b && !w) w = b[4].trim();
          j++;
        }
      }
      from = f;
      when = parseMailDate(w ?? undefined);
      i = j - 1;
      continue;
    }
    buf.push(lines[i]);
  }
  flush();
  return out;
}

const CODEISH =
  /^\s*[{}[\]]|^\s*"[^"]*"\s*:|^\s*<\/?\w|^\s*(?:function|const|let|var|import|def|class|SELECT|INSERT|UPDATE|<\?xml)\b|^\s{2,}\S|[;,{}]\s*$/;

/**
 * Pasted JSON, XML, logs and stack traces are evidence: their repeated lines
 * are structure, not boilerplate, and two payloads differing in one field are
 * not near-duplicates. Such blocks are kept verbatim and compared whole.
 */
export function looksStructured(paragraph: string): boolean {
  const lines = paragraph.split("\n").filter((l) => l.trim());
  if (lines.length < 3) return false;
  const hits = lines.filter((l) => CODEISH.test(l)).length;
  return hits / lines.length >= 0.6;
}

const lineKey = (s: string) => s.toLowerCase().replace(/\s+/g, " ").trim();

const tokens = (s: string) =>
  s
    .toLowerCase()
    .replace(/^\s*>+/gm, "")
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .trim()
    .split(" ")
    .filter(Boolean);

function shingles(s: string, n = 5): Set<string> {
  const t = tokens(s);
  const out = new Set<string>();
  for (let i = 0; i + n <= t.length; i++) out.add(t.slice(i, i + n).join(" "));
  return out;
}

const blockKey = (s: string) => tokens(s).join(" ");

function displayName(raw: string): string {
  const quotedName = /^"?([^"<]+?)"?\s*</.exec(raw);
  let v = (quotedName?.[1] ?? raw).replace(/<[^>]*>/g, "").trim();
  if (v.includes("@")) return v.toLowerCase();
  if (v.includes(","))
    v = v.split(",").reverse().join(" ").replace(/\s+/g, " ").trim();
  return v || "unknown";
}

export interface CompactMeta {
  externalId: string;
  title?: string;
  url?: string;
  opened?: string;
  updated?: string;
}

/**
 * Reduce a work item's messages to a de-duplicated, attributed turn list.
 * Deterministic — no model calls, same input always yields the same output.
 */
export function compactMessages(
  messages: RawMessage[],
  meta: CompactMeta,
  opts: CompactOptions = {},
): CompactedWorkItem {
  const boilerplateThreshold = opts.boilerplateThreshold ?? 3;
  const trackerThreshold = opts.trackerThreshold ?? 5;
  const nearRatio = opts.nearDuplicateRatio ?? 0.8;

  const bodies = messages.map((m) => normalizeBody(m.bodyText));
  const rawChars = bodies.reduce((a, b) => a + b.length, 0);
  const blocksPerMessage = bodies.map(splitQuotedBlocks);

  const lineFreq = new Map<string, number>();
  const urlFreq = new Map<string, number>();
  for (const blocks of blocksPerMessage)
    for (const b of blocks) {
      const seen = new Set<string>();
      for (const line of b.text.split("\n")) {
        const k = lineKey(line);
        if (k.length < 10 || seen.has(k)) continue;
        seen.add(k);
        lineFreq.set(k, (lineFreq.get(k) ?? 0) + 1);
      }
      for (const m of b.text.matchAll(/<(https?:\/\/[^>]+)>/g))
        urlFreq.set(m[1], (urlFreq.get(m[1]) ?? 0) + 1);
    }
  const boilerplate = new Set(
    [...lineFreq].filter(([, n]) => n >= boilerplateThreshold).map(([k]) => k),
  );
  const trackers = new Set(
    [...urlFreq].filter(([, n]) => n >= trackerThreshold).map(([u]) => u),
  );

  const detrack = (s: string) =>
    s
      .replace(/<(https?:\/\/[^>]+)>/g, (m, u) => (trackers.has(u) ? "" : m))

      .replace(/[ \t]{2,}/g, " ")
      .trim();

  const dropped = {
    automated: 0,
    auto_reply: 0,
    prior_transcript: 0,
    exact_duplicate_blocks: 0,
    near_duplicate_blocks: 0,
    boilerplate_lines: 0,
  };

  const emitted = new Set<string>();
  /**
   * Banners, rules and signatures are noise wherever they appear. A merely
   * repeated line is only noise on re-appearance — a ticket's own description
   * recurs once every later mail quotes it, and the original must survive.
   */
  const isNoise = (line: string) => {
    const s = line.trim();
    if (!s) return false;
    if (BANNERS.some((r) => r.test(s))) return true;
    if (RULE.test(s)) return true;
    if (POSTAL.test(s)) return true;
    if (SIGNATURE_LINE.test(s) && PHONE.test(s)) return true;
    const k = lineKey(s);
    if (boilerplate.has(k)) {
      if (emitted.has(k)) return true;
      emitted.add(k);
    }
    return false;
  };

  const seenBlocks = new Set<string>();
  const seenShingles = new Set<string>();
  const keepBlock = (s: string, structured = false) => {
    const k = blockKey(s);
    if (!k) return false;
    if (seenBlocks.has(k)) {
      dropped.exact_duplicate_blocks++;
      return false;
    }
    seenBlocks.add(k);
    if (structured) return true;
    const sh = shingles(s);
    if (sh.size >= 3) {
      let hit = 0;
      for (const g of sh) if (seenShingles.has(g)) hit++;
      if (hit / sh.size >= nearRatio) {
        dropped.near_duplicate_blocks++;
        return false;
      }
    }
    for (const g of sh) seenShingles.add(g);
    return true;
  };

  const skipped = messages.map((msg, idx) => {
    const body = bodies[idx];
    if (!body) return null;
    if (PRIOR_TRANSCRIPT.test(body)) return "prior_transcript" as const;
    if (opts.keepAutomated) return null;
    if (msg.automated) return "automated" as const;
    if (AUTO_REPLY.test(body) && body.length < 1200)
      return "auto_reply" as const;
    return null;
  });
  skipped.forEach((why, idx) => {
    if (!why) return;
    dropped[why]++;
    for (const line of bodies[idx].split("\n")) emitted.add(lineKey(line));
  });

  const turns: CompactTurn[] = [];
  const messageFilesPlaced = new Set<number>();
  let attachmentCount = 0;
  messages.forEach((msg, idx) => {
    const body = bodies[idx];
    if (!body || skipped[idx]) return;
    const internal = msg.visibility !== "public";
    const turnsBefore = turns.length;
    for (const block of blocksPerMessage[idx]) {
      const paragraphs = block.text
        .split(/\n\s*\n/)
        .map((p) => {
          if (looksStructured(p)) return p.replace(/\s+$/, "");
          return detrack(p)
            .split("\n")
            .map(detrack)
            .filter((l) => {
              if (!isNoise(l)) return true;
              dropped.boilerplate_lines++;
              return false;
            })
            .join("\n")
            .trim();
        })
        .filter(
          (p) => p.trim().length >= 3 && keepBlock(p, looksStructured(p)),
        );
      if (!paragraphs.length) continue;
      turns.push({
        n: turns.length + 1,
        speaker: block.quoted
          ? displayName(block.from ?? "unknown")
          : // authorLabel is the adapter's display name; author (a login or id)
            // is the fallback so a source that sets only that still names people
            (msg.authorLabel ??
            msg.author ??
            (internal ? "agent (internal)" : "support")),
        at:
          block.quoted && block.when
            ? block.when.toISOString()
            : (msg.createdAt ?? meta.opened ?? ""),
        kind: block.quoted ? "quoted" : internal ? "internal_note" : "reply",
        source_message: msg.externalId,
        text: paragraphs.join("\n\n"),
      });
      // files belong to the message, so they hang off its first surviving turn
      // rather than being repeated under every quoted hop below it
      if (!block.quoted && !messageFilesPlaced.has(idx)) {
        const files = normalizeAttachments(msg.attachments);
        if (files.length) {
          turns[turns.length - 1].attachments = files;
          attachmentCount += files.length;
        }
        messageFilesPlaced.add(idx);
      }
    }
    if (messageFilesPlaced.has(idx)) return;
    const files = normalizeAttachments(msg.attachments);
    if (!files.length) return;
    messageFilesPlaced.add(idx);
    attachmentCount += files.length;
    const own = turns.slice(turnsBefore).find((t) => t.kind !== "quoted");
    if (own) {
      own.attachments = files;
      return;
    }
    // every word of this message was a duplicate, but a file is not a word:
    // it gets its own turn so the reference survives
    turns.push({
      n: turns.length + 1,
      speaker:
        msg.authorLabel ??
        msg.author ??
        (internal ? "agent (internal)" : "support"),
      at: msg.createdAt ?? meta.opened ?? "",
      kind: internal ? "internal_note" : "reply",
      source_message: msg.externalId,
      text: "",
      attachments: files,
    });
  });

  const opened = meta.opened ? Date.parse(meta.opened) : NaN;
  const recovered = Number.isNaN(opened)
    ? 0
    : turns.filter((t) => t.kind === "quoted" && Date.parse(t.at) < opened)
        .length;

  return {
    ticket: {
      external_id: meta.externalId,
      title: meta.title,
      url: meta.url,
      opened: meta.opened,
      updated: meta.updated,
    },
    compaction: {
      source_messages: messages.length,
      turns: turns.length,
      raw_chars: rawChars,
      compact_chars: turns.reduce((a, t) => a + t.text.length, 0),
      dropped,
      recovered_earlier: recovered,
      attachments: attachmentCount,
    },
    speakers: [...new Set(turns.map((t) => t.speaker))],
    turns,
    prior_transcript_ids: messages
      .filter((m, i) => skipped[i] === "prior_transcript" && m.externalId)
      .map((m) => m.externalId as string),
  };
}

export function compactWorkItem(
  item: RawWorkItem,
  opts: CompactOptions = {},
): CompactedWorkItem {
  return compactMessages(
    item.messages,
    {
      externalId: item.externalId,
      title: item.title,
      url: item.externalUrl,
      opened: item.sourceCreatedAt,
      updated: item.sourceUpdatedAt,
    },
    opts,
  );
}

/** Below this much message text, reshaping a ticket buys nothing. */
export const COMPACT_MIN_CHARS = 8 * 1024;
/** And above it, compaction has to actually earn its place. */
export const COMPACT_MIN_SAVING = 0.2;

/**
 * Decide whether the model should read the compacted form instead of the raw
 * messages. Compaction is pure CPU — no network, no model call — so it is always
 * computed and then kept only when it demonstrably helps. A short ticket, or a
 * long one with no repetition, comes back byte-for-byte unchanged.
 */
export function compactForLlm(
  item: RawWorkItem,
  opts: CompactOptions = {},
): { item: RawWorkItem; compacted?: CompactedWorkItem } {
  const compacted = compactWorkItem(item, opts);
  const { raw_chars, compact_chars } = compacted.compaction;
  if (raw_chars < COMPACT_MIN_CHARS) return { item };
  const saving = raw_chars ? (raw_chars - compact_chars) / raw_chars : 0;
  if (saving < COMPACT_MIN_SAVING) return { item };
  return { item: { ...item, messages: [] }, compacted };
}

/**
 * Quoted turns older than the work item itself came from mail that predates the
 * ticket and exists nowhere else, so they read as their own timeline.
 */
export function splitPrologue(c: CompactedWorkItem): {
  prologue: CompactTurn[];
  thread: CompactTurn[];
} {
  const opened = c.ticket.opened ? Date.parse(c.ticket.opened) : NaN;
  if (Number.isNaN(opened)) return { prologue: [], thread: c.turns };
  const prologue: CompactTurn[] = [];
  const thread: CompactTurn[] = [];
  for (const t of c.turns) {
    const at = Date.parse(t.at);
    if (t.kind === "quoted" && !Number.isNaN(at) && at < opened)
      prologue.push(t);
    else thread.push(t);
  }
  prologue.sort((a, b) => a.at.localeCompare(b.at));
  return { prologue, thread };
}

const day = (s: string) => (s || "").slice(0, 10);

const tag = (t: CompactTurn) =>
  t.kind === "quoted"
    ? " ↩quoted"
    : t.kind === "internal_note"
      ? " ·internal"
      : "";

export function renderCompactScript(c: CompactedWorkItem): string {
  const { prologue, thread } = splitPrologue(c);
  const s = summarizeCompaction(c);
  const out: string[] = [
    `# ${c.ticket.title ?? "Work item"}   [#${c.ticket.external_id}]`,
    "",
    `${s.headline} · ${day(c.ticket.opened ?? "")} → ${day(c.ticket.updated ?? "")}`,
    [s.removed, s.recovered, s.files].filter(Boolean).join(" "),
    "",
  ];
  const line = (t: CompactTurn, withTag: boolean) =>
    `${t.speaker} (${day(t.at)})${withTag ? tag(t) : ""}:${
      t.text ? ` ${t.text.replace(/\n/g, "\n    ")}` : ""
    }\n` +
    (t.attachments?.length
      ? `    ↳ files: ${t.attachments.map(describeAttachment).join("; ")}\n`
      : "");
  if (prologue.length) {
    out.push(
      `## Earlier mail, recovered from quoted replies — ${prologue.length} message${prologue.length === 1 ? "" : "s"} that appear nowhere else on this ticket`,
      "",
    );
    for (const t of prologue) out.push(line(t, false));
    out.push(`## The ticket thread`, "");
  }
  for (const t of thread) out.push(line(t, true));
  return out.join("\n");
}

const esc = (s: string) =>
  s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const COLORS: Record<CompactTurn["kind"], string> = {
  reply: "#1a1a1a",
  internal_note: "#8a5a00",
  quoted: "#5a5a7a",
};

const kb = (n: number) => `${Math.max(1, Math.round(n / 1024))} KB`;

/**
 * Plain-language accounting of what changed. "Turns" and "blocks" are internal
 * vocabulary — a reader wants to know how much less there is to read, what was
 * taken away, and what was found.
 */
export function summarizeCompaction(c: CompactedWorkItem): {
  headline: string;
  removed: string;
  recovered: string;
  files: string;
} {
  const {
    raw_chars,
    compact_chars,
    source_messages,
    dropped: d,
  } = c.compaction;
  const saved = raw_chars
    ? Math.max(0, Math.round((100 * (raw_chars - compact_chars)) / raw_chars))
    : 0;
  const bits: string[] = [];
  const repeats = d.exact_duplicate_blocks + d.near_duplicate_blocks;
  if (repeats)
    bits.push(`${repeats} repeated quote${repeats === 1 ? "" : "s"}`);
  if (d.boilerplate_lines)
    bits.push(`${d.boilerplate_lines} signature/footer lines`);
  const auto = d.automated + d.auto_reply;
  if (auto) bits.push(`${auto} automated mail${auto === 1 ? "" : "s"}`);
  if (d.prior_transcript) bits.push("an earlier transcript");
  const files = c.compaction.attachments;
  return {
    headline: `${source_messages} messages · ${kb(compact_chars)} to read instead of ${kb(raw_chars)} (${saved}% less)`,
    files: files
      ? `${files} file${files === 1 ? "" : "s"} referenced by name — open them on the ticket.`
      : "",
    removed: bits.length ? `Removed ${bits.join(", ")}.` : "",
    recovered: c.compaction.recovered_earlier
      ? `Recovered ${c.compaction.recovered_earlier} older message${c.compaction.recovered_earlier === 1 ? "" : "s"} that survive only inside quoted replies.`
      : "",
  };
}

/** Freshdesk note bodies render HTML, so the script ships as markup, not markdown. */
export function renderCompactHtml(c: CompactedWorkItem): string {
  const { prologue, thread } = splitPrologue(c);
  const s = summarizeCompaction(c);
  const turn = (t: CompactTurn, withTag: boolean) =>
    `<p style="margin:0 0 10px 0"><strong style="color:${COLORS[t.kind]}">${esc(t.speaker)}</strong> ` +
    `<span style="color:#888">(${day(t.at)})${withTag ? esc(tag(t)) : ""}</span>:${t.text ? " " : ""}` +
    `${esc(t.text)
      .replace(/\n\s*\n/g, "<br><br>")
      .replace(/\n/g, "<br>")}` +
    (t.attachments?.length
      ? `<br><span style="color:#777">↳ files: ${esc(t.attachments.map(describeAttachment).join("; "))}</span>`
      : "") +
    `</p>`;
  const parts: string[] = [
    `<div><p><strong>Compacted transcript — ${esc(c.ticket.title ?? "")} [#${esc(c.ticket.external_id)}]</strong></p>`,
    `<p style="color:#666">${esc(s.headline)}<br>${esc([s.removed, s.recovered, s.files].filter(Boolean).join(" "))}<br>` +
      `Every word below is quoted verbatim — nothing was summarised or reworded. ` +
      `Generated by tachy ${TRANSCRIPT_MARKER}</p><hr>`,
  ];
  if (prologue.length) {
    parts.push(
      `<p><strong>Earlier mail, recovered from quoted replies</strong> — ${prologue.length} message${prologue.length === 1 ? "" : "s"} that appear nowhere else on this ticket</p>`,
    );
    for (const t of prologue) parts.push(turn(t, false));
    parts.push(`<hr><p><strong>The ticket thread</strong></p>`);
  }
  for (const t of thread) parts.push(turn(t, true));
  parts.push("</div>");
  return parts.join("\n");
}

/**
 * Split a rendered note at turn boundaries. Freshdesk documents no body limit,
 * so a long transcript is posted as a numbered series rather than gambling a
 * single oversized request.
 */
export function splitNoteBody(html: string, maxChars = 60000): string[] {
  if (html.length <= maxChars) return [html];
  const paragraphs = html.split("\n");
  const parts: string[] = [];
  let buf: string[] = [];
  let size = 0;
  for (const p of paragraphs) {
    if (size + p.length > maxChars && buf.length) {
      parts.push(buf.join("\n"));
      buf = [];
      size = 0;
    }
    buf.push(p);
    size += p.length + 1;
  }
  if (buf.length) parts.push(buf.join("\n"));
  return parts.map(
    (p, i) =>
      `<p style="color:#888">[compacted transcript ${i + 1}/${parts.length}]</p>\n${p}`,
  );
}
