import { z } from "zod";
import type { WorkItemSource } from "../sources/source";
import type { RawMessage } from "./raw";
import {
  SUMMARY_MARKER,
  escapeHtml,
  mutedLine,
  noteFooter,
  noteHeader,
  sectionRule,
  textToHtml,
} from "./note-html";

/**
 * What a ticket summary holds. The descriptions are the writing brief: they
 * reach the model both as the MCP tool's schema and in the flow step's prompt.
 */
export const ticketSummarySchema = z.object({
  problem: z
    .string()
    .min(1)
    .describe(
      "What the customer reported and its impact, in two to four sentences. Facts from the thread only.",
    ),
  status: z
    .string()
    .min(1)
    .describe(
      "Where the ticket stands now: resolved, waiting on whom, or blocked on what. One or two sentences.",
    ),
  timeline: z
    .array(
      z.object({
        date: z.string().describe("YYYY-MM-DD, taken from the message."),
        who: z
          .string()
          .optional()
          .describe("The person or team that acted, as named in the thread."),
        event: z.string().min(1).describe("What happened, in one sentence."),
      }),
    )
    .describe(
      "Key events, oldest first. Decisions, findings and hand-offs; not every message.",
    ),
  tried: z
    .array(
      z.object({
        action: z.string().min(1).describe("What was attempted or checked."),
        outcome: z
          .string()
          .min(1)
          .describe("Its result, or why it was ruled out."),
      }),
    )
    .describe(
      "What was already attempted or ruled out, including work tracked in linked Azure DevOps items. Empty when nothing was.",
    ),
});

export type TicketSummary = z.infer<typeof ticketSummarySchema>;

export interface SummarizedTicket {
  external_id: string;
  title?: string;
}

const CELL = "padding:4px 10px 4px 0;vertical-align:top";

function timelineHtml(timeline: TicketSummary["timeline"]): string {
  const rows = timeline.map(
    (entry) =>
      `<tr><td style="${CELL};white-space:nowrap;color:#777">${escapeHtml(entry.date)}</td>` +
      `<td style="${CELL}">${entry.who ? `<strong>${escapeHtml(entry.who)}</strong>: ` : ""}${escapeHtml(entry.event)}</td></tr>`,
  );
  return `<table style="border-collapse:collapse;margin:0 0 8px 0">${rows.join("")}</table>`;
}

function triedHtml(tried: TicketSummary["tried"]): string {
  const items = tried.map(
    (attempt) =>
      `<li style="margin:0 0 4px 0">${escapeHtml(attempt.action)}<br><span style="color:#777">${escapeHtml(attempt.outcome)}</span></li>`,
  );
  return `<ul style="margin:0 0 8px 0;padding-left:22px">${items.join("")}</ul>`;
}

/** The summary as one private-note body, stamped so the next one replaces it. */
export function renderSummaryHtml(
  ticket: SummarizedTicket,
  summary: TicketSummary,
): string {
  const sections = [
    noteHeader("Summary", ticket.title, ticket.external_id),
    sectionRule("Problem"),
    textToHtml(summary.problem),
    sectionRule("Current status"),
    textToHtml(summary.status),
  ];
  if (summary.timeline.length)
    sections.push(sectionRule("Timeline"), timelineHtml(summary.timeline));
  if (summary.tried.length)
    sections.push(sectionRule("Tried / ruled out"), triedHtml(summary.tried));
  sections.push(
    mutedLine(
      "Written by a model from the ticket thread; check it against the thread before acting on it.",
    ),
    noteFooter("Generated by tachy", SUMMARY_MARKER),
  );
  return `<div>${sections.join("\n")}</div>`;
}

/** The summary as plain text, for a flow step that reads it. */
export function renderSummaryText(summary: TicketSummary): string {
  const lines = [`Problem: ${summary.problem}`, `Status: ${summary.status}`];
  if (summary.timeline.length) {
    lines.push("Timeline:");
    for (const entry of summary.timeline)
      lines.push(
        `- ${entry.date}${entry.who ? ` ${entry.who}` : ""}: ${entry.event}`,
      );
  }
  if (summary.tried.length) {
    lines.push("Tried / ruled out:");
    for (const attempt of summary.tried)
      lines.push(`- ${attempt.action} -> ${attempt.outcome}`);
  }
  return lines.join("\n");
}

/** Source ids of the summaries an earlier run posted on this ticket. */
export function priorSummaryIds(messages: RawMessage[]): string[] {
  return messages
    .filter((message) => message.bodyText.includes(SUMMARY_MARKER))
    .flatMap((message) => (message.externalId ? [message.externalId] : []));
}

export interface ReplacedNotes {
  notes: number;
  replaced_previous?: number;
}

/**
 * Posts `bodies` as private notes, then deletes `priorIds`. The order matters:
 * an earlier note goes only once its replacement is on the ticket. A note that
 * cannot be deleted is left in place and not counted.
 */
export async function replaceNotes(
  source: Pick<WorkItemSource, "postNote" | "deleteNote">,
  externalId: string,
  bodies: string[],
  priorIds: string[],
): Promise<ReplacedNotes> {
  if (!source.postNote) throw new Error("source does not support notes");
  for (const body of bodies)
    await source.postNote(externalId, body, { private: true });
  const posted: ReplacedNotes = { notes: bodies.length };
  if (!source.deleteNote) return posted;
  let replaced = 0;
  for (const id of priorIds)
    await source.deleteNote(id).then(
      () => replaced++,
      () => {},
    );
  if (replaced) posted.replaced_previous = replaced;
  return posted;
}
