/**
 * The "Summarise ticket" flow step, with the model call stubbed: what it reads,
 * what it posts and replaces, and what stops it before a model is reached.
 */
import { afterAll, beforeEach, describe, expect, it, vi } from "vitest";
import { createFlow, flowAction, type FlowSubject } from "@tachy/core/flows";
import {
  addSourceConnection,
  registerSource,
  type RawWorkItem,
} from "@tachy/core/sources";
import { registerAgentFlowActions } from "../../packages/agent/src/flow-actions";
import { runAdvisory } from "../../packages/agent/src/advisory";
import { resetData, sql } from "../database";

vi.mock("../../packages/agent/src/advisory", async (original) => ({
  ...(await original<typeof import("../../packages/agent/src/advisory")>()),
  runAdvisory: vi.fn(),
}));

afterAll(() => sql.end());

const posted: string[] = [];
const deleted: string[] = [];
let thread: RawWorkItem["messages"] = [];
let takesNotes = true;

registerSource("fake-summary", () => ({
  type: "fake-summary",
  capabilities: { postNote: true, incrementalSync: false },
  async fetchItem() {
    return {
      externalId: "s-1",
      kind: "ticket" as const,
      title: "Scanner offline",
      raw: {},
      messages: thread,
    };
  },
  async listItems() {
    return { items: [] };
  },
  ...(takesNotes
    ? {
        async postNote(_id: string, body: string) {
          posted.push(body);
        },
        async deleteNote(id: string) {
          deleted.push(id);
        },
      }
    : {}),
}));

const answer = JSON.stringify({
  problem: "The scanner on dock 2 is offline.",
  status: "Waiting on a site visit.",
  timeline: [{ date: "2026-06-16", who: "Ana", event: "Reported it." }],
  tried: [{ action: "Power cycle", outcome: "No change." }],
});

const graph = {
  triggers: [{ id: "m", kind: "manual", params: {} }],
  steps: [],
};

let flowCount = 0;

async function context(modelCallsPerDay?: number) {
  const flow = await createFlow(
    {
      name: `summarise ${flowCount++}`,
      team_id: null,
      enabled: true,
      graph,
      ...(modelCallsPerDay === undefined
        ? {}
        : { model_calls_per_day: modelCallsPerDay }),
    },
    null,
  );
  return {
    flowId: flow.id,
    flowRunId: flow.id,
    scope: {},
    userId: null,
    item: {
      external_id: "s-1",
      connection: "summary-conn",
      source_type: "fake-summary",
    } as FlowSubject,
    signal: new AbortController().signal,
    log: () => {},
    enqueue: async () => null,
  };
}

beforeEach(async () => {
  await resetData();
  registerAgentFlowActions();
  posted.length = 0;
  deleted.length = 0;
  takesNotes = true;
  thread = [
    {
      externalId: "1",
      direction: "incoming",
      visibility: "public",
      authorLabel: "Ana",
      createdAt: "2026-06-16T08:00:00Z",
      bodyText: "The scanner on dock 2 is offline since this morning.",
    },
    {
      externalId: "old-summary",
      direction: "outgoing",
      visibility: "private",
      bodyText: "Summary ... Generated by tachy [tachy:summary]",
    },
  ];
  vi.mocked(runAdvisory).mockReset().mockResolvedValue(answer);
  await addSourceConnection({
    sourceType: "fake-summary",
    slug: "summary-conn",
    baseUrl: "https://example.invalid",
  });
});

describe("agent.summarize_item", () => {
  it("posts the summary, replaces the previous one and hands its text on", async () => {
    const step = flowAction("agent.summarize_item");
    const result = await step.run(await context(), step.params.parse({}));
    expect(result).toEqual({
      text: expect.stringContaining(
        "Problem: The scanner on dock 2 is offline.",
      ),
      posted: true,
      replaced: 1,
    });
    expect(posted).toHaveLength(1);
    expect(posted[0]).toContain("<strong>Tried / ruled out</strong>");
    expect(deleted).toEqual(["old-summary"]);
  });

  it("summarises from the thread, not from its own earlier summary", async () => {
    const step = flowAction("agent.summarize_item");
    await step.run(await context(), step.params.parse({}));
    const [advisory] = vi.mocked(runAdvisory).mock.calls[0];
    const prompt = advisory.prompt((text) => text);
    expect(prompt).toContain("offline since this morning");
    expect(prompt).not.toContain("[tachy:summary]");
    expect(advisory.mode).toBe("flow");
    expect(advisory.meta).toMatchObject({ flow_id: expect.any(String) });
  });

  it("keeps the summary in the run when told not to post", async () => {
    const step = flowAction("agent.summarize_item");
    const result = await step.run(
      await context(),
      step.params.parse({ post: false }),
    );
    expect(result).toMatchObject({ posted: false, replaced: 0 });
    expect(posted).toEqual([]);
    expect(deleted).toEqual([]);
  });

  it("fails the step on an unreadable answer, a failed call or no credential", async () => {
    const step = flowAction("agent.summarize_item");
    const run = async () => step.run(await context(), step.params.parse({}));
    vi.mocked(runAdvisory).mockResolvedValue("no json here");
    await expect(run()).rejects.toThrow(/no readable summary/);
    vi.mocked(runAdvisory).mockResolvedValue("");
    await expect(run()).rejects.toThrow(/model call failed/);
    vi.mocked(runAdvisory).mockResolvedValue(null);
    await expect(run()).rejects.toThrow(/no model credential/);
    expect(posted).toEqual([]);
  });

  it("is refused before it reaches a model once the flow's share is spent", async () => {
    const step = flowAction("agent.summarize_item");
    await expect(
      step.run(await context(0), step.params.parse({})),
    ).rejects.toThrow(/made its 0 model calls/);
    expect(runAdvisory).not.toHaveBeenCalled();
  });

  it("needs an item, and one whose source takes notes", async () => {
    const step = flowAction("agent.summarize_item");
    await expect(
      step.run({ ...(await context()), item: null }, step.params.parse({})),
    ).rejects.toThrow(/needs an item/);
    takesNotes = false;
    await expect(
      step.run(await context(), step.params.parse({})),
    ).rejects.toThrow(/cannot take notes/);
    expect(runAdvisory).not.toHaveBeenCalled();
  });
});
